import { createHash } from 'node:crypto';
import { canonicalJson } from '@devai-nyx/utils';

const SHA256 = /^[a-f0-9]{64}$/u;
const GIT_OBJECT = /^(?:[a-f0-9]{40}|[a-f0-9]{64})$/u;
const BASE64 = /^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/u;
const MODES = ['100644', '100755'];
const ERROR = 'release-certified-evidence-carrier-invalid';
const CARRIER_KIND = 'devai.release-certified-evidence-carrier-json.v1';
const CENSUS_KIND = 'devai.release-namespace-census-json.v1';
/** Raw stream identities are never carrier members; only declared output identities are. */
const FORBIDDEN_CENSUS_KEYS = ['stdout', 'stderr', 'bytes', 'bytes_base64', 'content'];

export interface CertifiedEvidenceByteDocument {
  readonly sha256: string;
  readonly size_bytes: number;
  readonly bytes_base64: string;
}

/** Protected derivation binding: the exact authority under which the census was realised. */
export interface CertifiedEvidenceDerivation {
  readonly repository: { readonly id: string; readonly commit: string; readonly tree: string };
  readonly candidate: { readonly commit: string; readonly tree: string };
  readonly task_policy_digest_sha256: string;
}

export interface CertifiedEvidenceCensusEntry {
  readonly path: string;
  readonly mode: '100644' | '100755';
  readonly sha256: string;
  readonly size_bytes: number;
  readonly task_node: string;
}

/** Digest-only census. It never carries generated bytes or raw stdout/stderr. */
export interface CertifiedEvidenceNamespaceCensus {
  readonly schemaVersion: '1.0.0';
  readonly kind: typeof CENSUS_KIND;
  readonly release_unit: string;
  readonly derivation: CertifiedEvidenceDerivation;
  readonly entries: readonly CertifiedEvidenceCensusEntry[];
}

export interface CertifiedEvidenceCarrier {
  readonly schemaVersion: '1.0.0';
  readonly kind: typeof CARRIER_KIND;
  readonly release_unit: string;
  readonly derivation: CertifiedEvidenceDerivation;
  readonly candidate_receipt: CertifiedEvidenceByteDocument;
  readonly task_policy: CertifiedEvidenceByteDocument;
  /** Sorted by sha256 so the population is order-free and duplicate-free. */
  readonly task_results: readonly CertifiedEvidenceByteDocument[];
  readonly namespace_census: CertifiedEvidenceByteDocument;
}

function fail(): never {
  throw new Error(ERROR);
}
function digest(value: Buffer): string {
  return createHash('sha256').update(value).digest('hex');
}
function canonical(value: unknown): Buffer {
  return Buffer.from(canonicalJson(value), 'utf8');
}
function bound(maximum: unknown): number {
  if (!Number.isSafeInteger(maximum) || (maximum as number) < 1) fail();
  return maximum as number;
}
function plain(value: unknown): Record<string, unknown> {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) fail();
  return value as Record<string, unknown>;
}
function document(value: unknown, maximum: number): CertifiedEvidenceByteDocument {
  const bytes = canonical(value);
  if (bytes.length < 1 || bytes.length > maximum) fail();
  return {
    sha256: digest(bytes),
    size_bytes: bytes.length,
    bytes_base64: bytes.toString('base64'),
  };
}
function decode(value: unknown, maximum: number): Buffer {
  const entry = plain(value);
  const size = entry.size_bytes;
  if (
    Object.keys(entry).length !== 3 ||
    typeof entry.sha256 !== 'string' ||
    !SHA256.test(entry.sha256) ||
    typeof size !== 'number' ||
    !Number.isSafeInteger(size) ||
    size < 1 ||
    size > maximum ||
    typeof entry.bytes_base64 !== 'string' ||
    !BASE64.test(entry.bytes_base64)
  )
    fail();
  const bytes = Buffer.from(entry.bytes_base64, 'base64');
  if (
    bytes.length !== size ||
    bytes.toString('base64') !== entry.bytes_base64 ||
    digest(bytes) !== entry.sha256
  )
    fail();
  try {
    if (
      !bytes.equals(canonical(JSON.parse(new TextDecoder('utf-8', { fatal: true }).decode(bytes))))
    )
      fail();
  } catch {
    fail();
  }
  return bytes;
}
function captureDerivation(value: unknown): CertifiedEvidenceDerivation {
  const derivation = plain(value);
  const repository = plain(derivation.repository);
  const candidate = plain(derivation.candidate);
  if (
    Object.keys(derivation).length !== 3 ||
    Object.keys(repository).length !== 3 ||
    Object.keys(candidate).length !== 2 ||
    typeof repository.id !== 'string' ||
    repository.id.length === 0 ||
    typeof repository.commit !== 'string' ||
    typeof repository.tree !== 'string' ||
    typeof candidate.commit !== 'string' ||
    typeof candidate.tree !== 'string' ||
    !GIT_OBJECT.test(candidate.commit) ||
    !GIT_OBJECT.test(candidate.tree) ||
    candidate.commit.length !== candidate.tree.length ||
    repository.commit !== candidate.commit ||
    repository.tree !== candidate.tree ||
    typeof derivation.task_policy_digest_sha256 !== 'string' ||
    !SHA256.test(derivation.task_policy_digest_sha256)
  )
    fail();
  return {
    repository: { id: repository.id, commit: repository.commit, tree: repository.tree },
    candidate: { commit: candidate.commit, tree: candidate.tree },
    task_policy_digest_sha256: derivation.task_policy_digest_sha256,
  };
}

/** The one authoritative census projection. Callers never hand-assemble this shape. */
export function finalizeCertifiedEvidenceNamespaceCensus(input: {
  readonly release_unit: string;
  readonly derivation: unknown;
  readonly entries: readonly {
    readonly path: string;
    readonly mode: string;
    readonly sha256: string;
    readonly size_bytes: number;
    readonly task_node: string;
  }[];
}): CertifiedEvidenceNamespaceCensus {
  if (typeof input.release_unit !== 'string' || input.release_unit.length === 0) fail();
  if (!Array.isArray(input.entries)) fail();
  const entries = input.entries.map((entry): CertifiedEvidenceCensusEntry => {
    const value = plain(entry);
    if (
      Object.keys(value).length !== 5 ||
      typeof value.path !== 'string' ||
      value.path.length === 0 ||
      value.path !== value.path.normalize('NFC') ||
      value.path.includes('\\') ||
      value.path.split('/').some((part) => part.length === 0 || part === '.' || part === '..') ||
      [...value.path].some(
        (character) => character.charCodeAt(0) < 32 || character.charCodeAt(0) === 127,
      ) ||
      typeof value.mode !== 'string' ||
      !MODES.includes(value.mode) ||
      typeof value.sha256 !== 'string' ||
      !SHA256.test(value.sha256) ||
      typeof value.size_bytes !== 'number' ||
      !Number.isSafeInteger(value.size_bytes) ||
      value.size_bytes < 0 ||
      typeof value.task_node !== 'string' ||
      value.task_node.length === 0
    )
      fail();
    return {
      path: value.path,
      mode: value.mode as '100644' | '100755',
      sha256: value.sha256,
      size_bytes: value.size_bytes,
      task_node: value.task_node,
    };
  });
  const paths = entries.map((entry) => entry.path);
  if (new Set(paths).size !== paths.length) fail();
  const sorted = [...entries].sort((a, b) =>
    Buffer.compare(Buffer.from(a.path), Buffer.from(b.path)),
  );
  return {
    schemaVersion: '1.0.0',
    kind: CENSUS_KIND,
    release_unit: input.release_unit,
    derivation: captureDerivation(input.derivation),
    entries: sorted,
  };
}

function assertCensus(
  bytes: Buffer,
  release_unit: string,
  derivation: CertifiedEvidenceDerivation,
): CertifiedEvidenceNamespaceCensus {
  const value = JSON.parse(bytes.toString('utf8')) as unknown;
  const census = plain(value);
  if (
    Object.keys(census).length !== 5 ||
    census.schemaVersion !== '1.0.0' ||
    census.kind !== CENSUS_KIND ||
    census.release_unit !== release_unit ||
    !Array.isArray(census.entries)
  )
    fail();
  // Reject any member that would smuggle raw generated bytes or streams into the carrier.
  for (const entry of census.entries)
    if (FORBIDDEN_CENSUS_KEYS.some((key) => key in plain(entry))) fail();
  const finalized = finalizeCertifiedEvidenceNamespaceCensus({
    release_unit,
    derivation: census.derivation,
    entries: census.entries as CertifiedEvidenceCensusEntry[],
  });
  if (
    canonicalJson(finalized) !== canonicalJson(value) ||
    canonicalJson(finalized.derivation) !== canonicalJson(derivation)
  )
    fail();
  return finalized;
}

/** Exact, duplicate-free, order-free result population declared by the candidate receipt. */
function receiptResultDigests(receipt: unknown): readonly string[] {
  const value = plain(receipt);
  const tasks = value.tasks;
  if (!Array.isArray(tasks) || tasks.length === 0) fail();
  const values = tasks.map((task) => {
    const entry = plain(task);
    if (typeof entry.resultDigest !== 'string' || !SHA256.test(entry.resultDigest)) fail();
    return entry.resultDigest;
  });
  if (new Set(values).size !== values.length) fail();
  return [...values].sort();
}

function assertReceiptPolicy(receipt: unknown, derivation: CertifiedEvidenceDerivation): void {
  const value = plain(receipt);
  const repository = plain(value.repository);
  if (
    value.taskPolicyDigest !== derivation.task_policy_digest_sha256 ||
    repository.id !== derivation.repository.id ||
    repository.commit !== derivation.repository.commit ||
    repository.tree !== derivation.repository.tree
  )
    fail();
}

function sortedResults(
  documents: readonly CertifiedEvidenceByteDocument[],
): readonly CertifiedEvidenceByteDocument[] {
  return [...documents].sort((a, b) => (a.sha256 < b.sha256 ? -1 : a.sha256 > b.sha256 ? 1 : 0));
}

function assertResultPopulation(
  documents: readonly { readonly sha256: string }[],
  expected: readonly string[],
): void {
  const observed = documents.map((document) => document.sha256);
  if (
    observed.length !== expected.length ||
    new Set(observed).size !== observed.length ||
    observed.some((value, index) => value !== expected[index])
  )
    fail();
}

/** Pure carrier construction; persistence and signing stay in their protected host boundaries. */
export function createCertifiedEvidenceCarrier(input: {
  readonly release_unit: string;
  readonly derivation: unknown;
  readonly candidate_receipt: unknown;
  readonly task_policy: unknown;
  readonly task_results: readonly unknown[];
  readonly namespace_census: unknown;
  readonly maximum_bytes: number;
}): Buffer {
  const maximum = bound(input.maximum_bytes);
  if (
    typeof input.release_unit !== 'string' ||
    input.release_unit.length === 0 ||
    !Array.isArray(input.task_results)
  )
    fail();
  const derivation = captureDerivation(input.derivation);
  assertReceiptPolicy(input.candidate_receipt, derivation);
  if (digest(canonical(input.task_policy)) !== derivation.task_policy_digest_sha256) fail();
  const candidateReceipt = document(input.candidate_receipt, maximum);
  const taskPolicy = document(input.task_policy, maximum);
  const results = sortedResults(input.task_results.map((result) => document(result, maximum)));
  const namespaceCensus = document(
    finalizeCertifiedEvidenceNamespaceCensus({
      release_unit: input.release_unit,
      derivation,
      entries: (plain(input.namespace_census).entries ?? fail()) as CertifiedEvidenceCensusEntry[],
    }),
    maximum,
  );
  assertResultPopulation(results, receiptResultDigests(input.candidate_receipt));
  const carrier: CertifiedEvidenceCarrier = {
    schemaVersion: '1.0.0',
    kind: CARRIER_KIND,
    release_unit: input.release_unit,
    derivation,
    candidate_receipt: candidateReceipt,
    task_policy: taskPolicy,
    task_results: results,
    namespace_census: namespaceCensus,
  };
  const bytes = canonical(carrier);
  if (bytes.length > maximum) fail();
  return bytes;
}

/** Decodes only canonical, self-authenticating documents and returns detached byte copies. */
export function readCertifiedEvidenceCarrier(
  bytes: Buffer,
  maximum_bytes: number,
): {
  readonly carrier: CertifiedEvidenceCarrier;
  readonly candidate_receipt: Buffer;
  readonly task_policy: Buffer;
  readonly task_results: readonly Buffer[];
  readonly namespace_census: Buffer;
  readonly census: CertifiedEvidenceNamespaceCensus;
  readonly derivation_binding_digest_sha256: string;
} {
  const maximum = bound(maximum_bytes);
  if (!Buffer.isBuffer(bytes) || bytes.length < 1 || bytes.length > maximum) fail();
  let value: unknown;
  try {
    value = JSON.parse(new TextDecoder('utf-8', { fatal: true }).decode(bytes));
  } catch {
    fail();
  }
  const record = plain(value);
  if (!bytes.equals(canonical(value))) fail();
  const carrier = record as unknown as CertifiedEvidenceCarrier;
  if (
    Object.keys(record).length !== 8 ||
    carrier.schemaVersion !== '1.0.0' ||
    carrier.kind !== CARRIER_KIND ||
    typeof carrier.release_unit !== 'string' ||
    carrier.release_unit.length === 0 ||
    !Array.isArray(carrier.task_results) ||
    carrier.task_results.length === 0
  )
    fail();
  const derivation = captureDerivation(carrier.derivation);
  const candidateReceipt = decode(carrier.candidate_receipt, maximum);
  const taskPolicy = decode(carrier.task_policy, maximum);
  const results = carrier.task_results.map((result) => decode(result, maximum));
  const namespaceCensus = decode(carrier.namespace_census, maximum);
  const receipt = JSON.parse(candidateReceipt.toString('utf8')) as unknown;
  assertReceiptPolicy(receipt, derivation);
  if (digest(taskPolicy) !== derivation.task_policy_digest_sha256) fail();
  assertResultPopulation(
    results.map((result) => ({ sha256: digest(result) })),
    receiptResultDigests(receipt),
  );
  // Sorted-by-digest emission is part of the format, not an incidental caller order.
  if (canonicalJson(carrier.task_results) !== canonicalJson(sortedResults(carrier.task_results)))
    fail();
  const census = assertCensus(namespaceCensus, carrier.release_unit, derivation);
  return {
    carrier: JSON.parse(canonicalJson(carrier)) as CertifiedEvidenceCarrier,
    candidate_receipt: Buffer.from(candidateReceipt),
    task_policy: Buffer.from(taskPolicy),
    task_results: results.map((result) => Buffer.from(result)),
    namespace_census: Buffer.from(namespaceCensus),
    census,
    derivation_binding_digest_sha256: digest(canonical(derivation)),
  };
}
