import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Curated sections, each labelled literally (docs-ia.sidebar-curated).
const sidebars: SidebarsConfig = {
  docsSidebar: [
    { type: 'category', label: 'Start', items: [{ type: 'autogenerated', dirName: 'start' }] },
    { type: 'category', label: 'Theory', items: [{ type: 'autogenerated', dirName: 'theory' }] },
    { type: 'category', label: 'Roles', items: [{ type: 'autogenerated', dirName: 'roles' }] },
    {
      type: 'category',
      label: 'Adopters',
      items: [{ type: 'autogenerated', dirName: 'adopters' }],
    },
    { type: 'category', label: 'Dev', items: [{ type: 'autogenerated', dirName: 'dev' }] },
    {
      type: 'category',
      label: 'Reference',
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
  ],
};

export default sidebars;
