import {
  authorityBindings,
  subjectGroups,
  defined,
  rule,
  harnessSubject,
  fsSelector,
  machineSubject,
  gitSelector,
  dbSelector,
} from './policy-support.js';
import type { HumanSubjects } from './policy-core-rules.js';

/** Additive extension rules: root path authority for engineers and architects, and the per-group harness, machine, git and database grants. */
export function buildAdditiveAuthorityRules(input: {
  readonly repositoryId: ReturnType<typeof authorityBindings>['repository_id'];
  readonly groups: ReturnType<typeof subjectGroups>;
  readonly human: HumanSubjects;
}) {
  const { repositoryId, groups, human } = input;
  const rootEngineerPaths = [
    'package.json',
    'pnpm-lock.yaml',
    'pnpm-workspace.yaml',
    'tsconfig*.json',
    'vitest*.ts',
    'eslint.config.*',
    '.prettier*',
  ];
  const rootArchitectPaths = [
    'README.md',
    'AGENTS.md',
    'CLAUDE.md',
    'SECURITY.md',
    'CHANGELOG.md',
    '.changeset/**',
  ];
  const additiveRules = defined([
    rule({
      id: 'adopter-git-ref-work-task-spawn-1',
      origin: 'additive-extension',
      precedence: 500,
      actionIds: ['round run', 'task start'],
      selector: gitSelector(repositoryId),
      subjects: [harnessSubject(['engineer'])],
      rationale: 'Adopter typed git-ref authority for work task spawn.',
    }),
    rule({
      id: 'adopter-git-ref-experimental-dispatch-1',
      origin: 'additive-extension',
      precedence: 500,
      actionIds: ['round dispatch'],
      selector: gitSelector(repositoryId),
      subjects: [harnessSubject(['owner', 'architect', 'inspector', 'engineer'])],
      consent: { write: true, allow_publish: false, experimental: true },
      rationale: 'Typed git-ref authority for experimental attempt worktrees (ADR-MDL-0005 D-3).',
    }),
    rule({
      id: 'adopter-git-ref-work-task-complete-1',
      origin: 'additive-extension',
      precedence: 500,
      actionIds: ['task finish'],
      selector: gitSelector(repositoryId),
      subjects: [harnessSubject(['engineer'])],
      rationale: 'Adopter typed git-ref authority for work task complete.',
    }),
    rule({
      id: 'adopter-git-ref-work-task-escalate-1',
      origin: 'additive-extension',
      precedence: 500,
      actionIds: ['task escalate'],
      selector: gitSelector(repositoryId),
      subjects: [harnessSubject(['engineer'])],
      rationale:
        'Typed git-ref authority to release an escalated agent task attempt worktree (ADR-MDL-0007).',
    }),
    rule({
      id: 'adopter-git-ref-round-ratify-1',
      origin: 'additive-extension',
      precedence: 500,
      actionIds: ['round ratify'],
      selector: gitSelector(repositoryId),
      subjects: [harnessSubject(['owner', 'architect'])],
      rationale:
        'Typed git-ref authority to release a rejected agent attempt worktree (ADR-MDL-0007).',
    }),
    rule({
      id: 'adopter-git-ref-experimental-dispose-1',
      origin: 'additive-extension',
      precedence: 500,
      actionIds: ['round dispatch dispose'],
      selector: gitSelector(repositoryId),
      subjects: [harnessSubject(['owner'])],
      consent: { write: true, allow_publish: false, experimental: true },
      rationale:
        'Typed git-ref authority to release the attempt worktrees of a disposed experimental task (ADR-MDL-0007).',
    }),
    rule({
      id: 'adopter-git-ref-verify-translation-1',
      origin: 'additive-extension',
      precedence: 500,
      actionIds: ['check'],
      selector: gitSelector(repositoryId),
      subjects: [harnessSubject(['inspector'])],
      rationale: 'Adopter typed git-ref authority for verify translation.',
    }),
    rule({
      id: 'adopter-db-work-task-spawn-1',
      origin: 'additive-extension',
      precedence: 500,
      actionIds: ['task start'],
      selector: dbSelector(),
      subjects: [harnessSubject(['engineer'])],
      rationale: 'Adopter typed db authority for work task spawn.',
    }),
    rule({
      id: 'adopter-db-verify-translation-1',
      origin: 'additive-extension',
      precedence: 500,
      actionIds: ['check'],
      selector: dbSelector(),
      subjects: [harnessSubject(['inspector'])],
      rationale: 'Adopter typed db authority for verify translation.',
    }),
    rule({
      id: 'adopter-engineer-packages',
      origin: 'additive-extension',
      precedence: 500,
      actionIds: groups.engineer,
      selector: fsSelector(repositoryId, 'packages/**'),
      subjects: [...human('engineer'), machineSubject('harness')],
      rationale: 'Adopter Engineer implementation authority.',
    }),
    rule({
      id: 'adopter-engineer-scripts',
      origin: 'additive-extension',
      precedence: 500,
      actionIds: groups.engineer,
      selector: fsSelector(repositoryId, 'scripts/**'),
      subjects: [...human('engineer'), machineSubject('harness')],
      rationale: 'Adopter Engineer tooling authority.',
    }),
    rule({
      id: 'adopter-engineer-workflows',
      origin: 'additive-extension',
      precedence: 500,
      actionIds: groups.engineer,
      selector: fsSelector(repositoryId, '.github/**'),
      subjects: [...human('engineer'), machineSubject('harness')],
      rationale: 'Adopter Engineer workflow implementation authority.',
    }),
    rule({
      id: 'adopter-binding-init-harness-ci-root',
      origin: 'additive-extension',
      precedence: 500,
      actionIds: ['init apply harness', 'init bind', 'init upgrade'],
      selector: fsSelector(repositoryId, '.github'),
      subjects: [machineSubject('binding')],
      rationale: 'Derived binding authority for the canonical init harness CI scaffold root.',
    }),
    rule({
      id: 'adopter-binding-init-harness-ci',
      origin: 'additive-extension',
      precedence: 500,
      actionIds: ['init apply harness', 'init bind', 'init upgrade'],
      selector: fsSelector(repositoryId, '.github/**'),
      subjects: [machineSubject('binding')],
      rationale: 'Derived binding authority for canonical init harness CI scaffold outputs.',
    }),
    ...[
      '.agents',
      '.agents/skills',
      '.agents/skills/**',
      '.claude',
      '.claude/skills',
      '.claude/skills/**',
    ].map((path, index) =>
      rule({
        id: `adopter-binding-init-harness-skills-${String(index + 1)}`,
        origin: 'additive-extension',
        precedence: 500,
        actionIds: ['init apply harness'],
        selector: fsSelector(repositoryId, path),
        subjects: [machineSubject('binding')],
        rationale:
          'Derived binding authority for the canonical Codex and Claude recipe adapter roots.',
      }),
    ),
    ...[
      '.git/hooks',
      '.git/hooks/**',
      '.git/devai',
      '.git/devai/**',
      '.husky',
      '.husky/**',
      '.devai/config',
      '.devai/config/post-merge-host-adapter.json',
    ].map((path, index) =>
      rule({
        id: `adopter-architect-hooks-${String(index + 1)}`,
        origin: 'additive-extension',
        precedence: 500,
        actionIds: ['init apply architect', 'init bind', 'init upgrade'],
        selector: fsSelector(repositoryId, path),
        subjects: [...human('architect'), machineSubject('binding')],
        rationale:
          'Adopter Architect authority for the exact local hook and host-adapter installation action.',
      }),
    ),
    ...rootEngineerPaths.map((path, index) =>
      rule({
        id: `adopter-engineer-root-${String(index + 1)}`,
        origin: 'additive-extension',
        precedence: 500,
        actionIds: groups.engineer,
        selector: fsSelector(repositoryId, path),
        subjects: [...human('engineer'), machineSubject('harness')],
        rationale: 'Adopter Engineer root tooling authority.',
      }),
    ),
    ...rootArchitectPaths.map((path, index) =>
      rule({
        id: `adopter-architect-root-${String(index + 1)}`,
        origin: 'additive-extension',
        precedence: 650,
        actionIds: groups.architect,
        selector: fsSelector(repositoryId, path),
        subjects: human('architect'),
        rationale: 'Adopter source Architect authority.',
      }),
    ),
    rule({
      id: 'adopter-db-sense-migrate-1',
      origin: 'additive-extension',
      precedence: 500,
      actionIds: ['sense migrate'],
      selector: dbSelector(),
      subjects: human('engineer'),
      rationale: 'Typed database authority for sense migrate.',
    }),
    rule({
      id: 'adopter-remote-sense-run-1',
      origin: 'additive-extension',
      precedence: 500,
      actionIds: ['sense run'],
      selector: {
        kind: 'remote',
        system_id: 'sensor-runtime',
        endpoint_ids: ['selected-kind'],
        operation_ids: ['invoke'],
        publication: true,
      },
      subjects: [machineSubject('harness')],
      consent: { write: true, allow_publish: true, experimental: false },
      rationale: 'Typed remote authority for sense run.',
    }),
    rule({
      id: 'adopter-remote-round-dispatch-1',
      origin: 'additive-extension',
      precedence: 500,
      actionIds: ['round dispatch'],
      selector: {
        kind: 'remote',
        system_id: 'local-command',
        endpoint_ids: ['experimental-agent'],
        operation_ids: ['invoke'],
        publication: false,
      },
      subjects: [machineSubject('harness')],
      consent: { write: true, allow_publish: false, experimental: true },
      rationale:
        'Typed remote authority for the exact experimental agent CLI attempt of an admitted task (ADR-MDL-0005 D-10).',
    }),
    rule({
      id: 'adopter-remote-round-run-1',
      origin: 'additive-extension',
      precedence: 500,
      actionIds: ['round run'],
      selector: {
        kind: 'remote',
        system_id: 'local-command',
        endpoint_ids: ['routine-executor'],
        operation_ids: ['invoke'],
        publication: false,
      },
      subjects: [machineSubject('harness')],
      rationale: 'Typed remote authority for the exact task routine selected by the round runner.',
    }),
    rule({
      id: 'adopter-remote-evidence-record-1',
      origin: 'additive-extension',
      precedence: 500,
      actionIds: ['evidence record'],
      selector: {
        kind: 'remote',
        system_id: 'local-command',
        endpoint_ids: ['test-runner'],
        operation_ids: ['invoke'],
        publication: false,
      },
      subjects: [machineSubject('harness')],
      rationale: 'Typed remote authority for the exact test command declared by evidence record.',
    }),
    rule({
      id: 'adopter-db-task-finish-1',
      origin: 'additive-extension',
      precedence: 500,
      actionIds: ['task finish'],
      selector: dbSelector(),
      subjects: [harnessSubject(['engineer'])],
      rationale: 'Typed database authority for task finish.',
    }),
  ]);
  return additiveRules;
}
