/** Schemas reachable from the current CLI and its runtime services. */
export const ROSTER = [
  'action-registry.schema.json',
  'action-result.schema.json',
  'actions-list-output.schema.json',
  'adopter-policy.schema.json',
  'adr.schema.json',
  'agent-run.schema.json',
  'api-map.schema.json',
  'assessment.schema.json',
  'audit-observation-result.schema.json',
  'authority-policy.schema.json',
  'authority-session.schema.json',
  'check-suites.schema.json',
  'common-defs.schema.json',
  'coverage-matrix.schema.json',
  'data-model-inventory.schema.json',
  'dep-graph.schema.json',
  'error.schema.json',
  'evidence.schema.json',
  'forbidden-action-authorizations.schema.json',
  'forbidden-actions.schema.json',
  'github-issues-tracking-config.schema.json',
  'github-issues-tracking-policy.schema.json',
  'glob-guards.schema.json',
  'glossary-entry.schema.json',
  'governance-event-segment.schema.json',
  'governance-event.schema.json',
  'governance-projection-batch.schema.json',
  'governance-projection-status.schema.json',
  'inv-candidate.schema.json',
  'invariant.schema.json',
  'inventory.schema.json',
  'journey.schema.json',
  'local-evidence-manifest.schema.json',
  'meta.schema.json',
  'model-runtime-registry.schema.json',
  'module-blueprint.schema.json',
  'mutation-intent.schema.json',
  'mutation-scenario.schema.json',
  'phase-closure.schema.json',
  'proof-epoch.schema.json',
  'project-config.schema.json',
  'rbac-inventory.schema.json',
  'record-meta.schema.json',
  'release-control.schema.json',
  'repo-introspection.schema.json',
  'rgr.schema.json',
  'round-execution.schema.json',
  'round-tracking-activation.schema.json',
  'routes-inventory.schema.json',
  'rtd-manifest.schema.json',
  'runtime-charter.schema.json',
  'scorecard-na-config.schema.json',
  'scorecard.schema.json',
  'sense-presets.schema.json',
  'sensor-reading.schema.json',
  'sensor-registry.schema.json',
  'subprocess-effects.schema.json',
  'task-execution-evidence.schema.json',
  'task.schema.json',
  'test-weakening-config.schema.json',
  'trace.schema.json',
  'triage.schema.json',
  'triage-classify-result.schema.json',
  'translation-witness.schema.json',
  'use-cases.schema.json',
  'validation-result.schema.json',
] as const;

export type SchemaName = (typeof ROSTER)[number] | (string & {});

export const INFRASTRUCTURE: readonly SchemaName[] = [
  'common-defs.schema.json',
  'record-meta.schema.json',
];
