import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, aroundEach, describe, expect, it } from 'vitest';
import {
  buildBootstrapPlan,
  executeBootstrapPlan,
  reconcileProjectConfig,
  resolveCanonicalPolicyContent,
  validateCanonicalPolicyContent,
  type BootstrapPlan,
  type CanonicalPolicyFile,
} from '../../src/bootstrap/index.js';
import { withAuthorityHostTestScope } from './authority-host-test-scope.js';

const roots: string[] = [];

aroundEach((runTest) => withAuthorityHostTestScope(runTest));
afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

function target(): string {
  const root = mkdtempSync(join(tmpdir(), 'devai-bootstrap-runtime-'));
  roots.push(root);
  return root;
}

function plannedContent(plan: BootstrapPlan, path: string): string {
  const entry = plan.entries.find((item) => item.path === path);
  if (entry === undefined || entry.content === null) {
    throw new Error(`bootstrap plan carries no content for ${path}`);
  }
  return entry.content;
}

/**
 * Result rosters are a declared ordering guarantee, not an accident of the plan
 * walk. Assert the walk order really differs from the sorted order first, so a
 * roster that merely echoes the walk cannot pass by coincidence.
 */
function expectSortedRoster(actual: readonly string[], plan: BootstrapPlan): void {
  const selected = new Set(actual);
  const walkOrder = plan.entries.map((entry) => entry.path).filter((path) => selected.has(path));
  const sorted = [...walkOrder].sort();
  expect(walkOrder).not.toEqual(sorted);
  expect(actual).toEqual(sorted);
}

describe('buildBootstrapPlan: adopter version identity', () => {
  it('stamps the fallback version onto every generated identity surface', () => {
    const plan = buildBootstrapPlan({ targetRoot: target() });
    expect(plan.devai_version).toBe('0.0.0');
    expect(JSON.parse(plannedContent(plan, '.devai/config/project.json'))).toMatchObject({
      devai_version: '0.0.0',
    });
    expect(plannedContent(plan, 'record/proofs/README.md')).toContain('Generated by DEVAI v0.0.0.');
  });

  it('stamps a supplied version onto the same surfaces', () => {
    const plan = buildBootstrapPlan({ targetRoot: target(), version: '1.2.1' });
    expect(plan.devai_version).toBe('1.2.1');
    expect(JSON.parse(plannedContent(plan, '.devai/config/project.json'))).toMatchObject({
      devai_version: '1.2.1',
    });
    expect(plannedContent(plan, 'record/proofs/README.md')).toContain('Generated by DEVAI v1.2.1.');
  });
});

describe('reconcileProjectConfig: framework keys without invented declarations', () => {
  it('omits the constitution key entirely when no binding is resolved', () => {
    const reconciled = reconcileProjectConfig({}, { version: '1.2.1' });
    // An `undefined` constitution key would still be an own property, which
    // makes the plan's deep-equality check report a spurious rewrite.
    expect(Object.keys(reconciled)).not.toContain('constitution');
    expect('constitution' in reconciled).toBe(false);
    expect(reconciled).toStrictEqual({
      schemaVersion: '1.0.0',
      project_type: 'runtime-host',
      authority_enforcement: { mode: 'cli-only' },
      profile: 'tier3',
      devai_version: '1.2.1',
    });
  });

  it('carries an adopter-declared constitution forward when none is supplied', () => {
    const pin = { version: '1.0.0', sha256: 'a'.repeat(64) };
    const reconciled = reconcileProjectConfig({ constitution: pin }, { version: '1.2.1' });
    expect(reconciled['constitution']).toStrictEqual(pin);
  });

  it('lets a resolved binding replace the adopter-declared constitution', () => {
    const pin = { version: '2.0.0', sha256: 'b'.repeat(64) };
    const reconciled = reconcileProjectConfig(
      { constitution: { version: '1.0.0', sha256: 'a'.repeat(64) } },
      { version: '1.2.1', constitution: pin },
    );
    expect(reconciled['constitution']).toStrictEqual(pin);
  });
});

describe('validateCanonicalPolicyContent: roster and parse boundaries', () => {
  const domainFixture = {
    schemaVersion: '1.0.0',
    core: ['CORE'],
    framework: ['DEVAI'],
    client: [],
  } as const;

  it.each(['core', 'framework', 'client'] as const)(
    'refuses a %s roster whose members are length-bearing non-strings',
    (key) => {
      // A nested array is truthy and reports a positive `length`, so a roster
      // guard that only measures length would admit it as a domain name.
      const document = { ...domainFixture, [key]: [['CORE']] };
      expect(() =>
        validateCanonicalPolicyContent('domains.json', JSON.stringify(document)),
      ).toThrow('canonical policy domains.json failed schema validation');
    },
  );

  it.each(['core', 'framework', 'client'] as const)(
    'refuses a %s roster carrying a numeric member',
    (key) => {
      const document = { ...domainFixture, [key]: [7] };
      expect(() =>
        validateCanonicalPolicyContent('domains.json', JSON.stringify(document)),
      ).toThrow('canonical policy domains.json failed schema validation');
    },
  );

  it.each([
    ['thresholds.json', 'a truncated document', '{"schemaVersion":'],
    ['thresholds.json', 'a trailing-comma document', '{"schemaVersion":"1.0.0",}'],
    ['domains.json', 'an empty document', ''],
    ['glob-guards.json', 'a bare identifier', 'undefined'],
  ] as const)('reports the underlying parse failure for %s given %s', (file, _name, bytes) => {
    // The adopter has to see *why* the canonical bytes are unreadable; a bare
    // "failed schema validation" hides a truncated or corrupted policy file.
    expect(() => validateCanonicalPolicyContent(file, bytes)).toThrow(
      new RegExp(
        `^canonical policy ${file.replace('.', '\\.')} failed schema validation: \\S`,
        'u',
      ),
    );
  });

  it('fails closed for a bootstrap policy file with no validator of any kind', () => {
    // Enrolling a file in the bootstrap roster without registering a schema (or
    // an inline validator) must refuse the bytes rather than materialize them
    // unchecked into an adopter repository.
    const unregistered = 'check-suites.json' as unknown as Parameters<
      typeof validateCanonicalPolicyContent
    >[0];
    expect(() => validateCanonicalPolicyContent(unregistered, '{"schemaVersion":"1.0.0"}')).toThrow(
      'canonical policy check-suites.json failed schema validation',
    );
  });

  it('does not lend one policy file the validator of another', () => {
    // Canonical thresholds bytes are a valid thresholds document and nothing
    // else; accepting them under a different file name would let any policy
    // borrow a passing shape from an unrelated schema.
    const unregistered = 'check-suites.json' as unknown as Parameters<
      typeof validateCanonicalPolicyContent
    >[0];
    expect(() =>
      validateCanonicalPolicyContent(
        unregistered,
        resolveCanonicalPolicyContent('thresholds.json'),
      ),
    ).toThrow('canonical policy check-suites.json failed schema validation');
  });
});

describe('resolveCanonicalPolicyContent: unavailable canonical sources', () => {
  it('names the missing canonical policy when no candidate resolves', () => {
    const absent = 'devai-absent-policy.json' as unknown as CanonicalPolicyFile;
    expect(() => resolveCanonicalPolicyContent(absent)).toThrow(
      'canonical policy source unavailable: law/policy/devai-absent-policy.json',
    );
  });
});

describe('buildBootstrapPlan: seeded adopter content', () => {
  it('terminates project.json with a newline at canonical indentation', () => {
    const bytes = plannedContent(
      buildBootstrapPlan({ targetRoot: target(), version: '1.2.1' }),
      '.devai/config/project.json',
    );
    expect(bytes.endsWith('\n')).toBe(true);
    expect(bytes).toBe(`${JSON.stringify(JSON.parse(bytes), null, 2)}\n`);
  });

  it('seeds identical, non-empty agent instructions for both host entry points', () => {
    const plan = buildBootstrapPlan({ targetRoot: target(), version: '1.2.1', profile: 'tier3' });
    const agents = plannedContent(plan, 'AGENTS.md');
    expect(agents).toBe(plannedContent(plan, 'CLAUDE.md'));
    expect(agents).toBe(
      '# Agent instructions\n\n' +
        'Follow Constitution Article 6 role separation: Owner, Architect, Inspector,\n' +
        'Engineer, and Auditor. Read README.md, law/constitution.md, law/adr, and\n' +
        'law/schemas before changing governed repository state.\n',
    );
  });

  it.each([
    ['record/proofs/README.md', 'proofs', 'machine only'],
    ['record/derived/inventory/README.md', 'inventory', 'regeneration subsystem only'],
    ['scratch/worktrees/README.md', 'worktrees', 'ephemeral'],
    ['law/glossary/README.md', 'glossary', 'Owner and Architect, jointly'],
    ['work/audit/README.md', 'audit', 'Auditor'],
  ])('stamps %s with its owning authority verbatim', (path, name, authority) => {
    const plan = buildBootstrapPlan({ targetRoot: target(), version: '1.2.1', profile: 'tier3' });
    expect(plannedContent(plan, path)).toBe(
      `# ${name}\n\n**Authority:** ${authority} (Constitution Article 6).\n\n` +
        'Content is intentionally empty until authored. Generated by DEVAI v1.2.1.\n',
    );
  });
});

describe('executeBootstrapPlan: .gitignore merge boundaries', () => {
  it('does not prepend a blank line when the adopter .gitignore is empty', () => {
    const root = target();
    writeFileSync(join(root, '.gitignore'), '');
    const result = executeBootstrapPlan(
      buildBootstrapPlan({ targetRoot: root, version: '1.2.1' }),
      { force: true },
    );
    expect(result.overwritten).toContain('.gitignore');
    expect(readFileSync(join(root, '.gitignore'), 'utf8')).toBe('scratch/\n');
  });
});

describe('executeBootstrapPlan: deterministic result rosters', () => {
  it('reports created paths sorted rather than in plan-walk order', () => {
    const root = target();
    const plan = buildBootstrapPlan({ targetRoot: root, version: '1.2.1', profile: 'tier3' });
    const result = executeBootstrapPlan(plan);
    expect(result.created.length).toBeGreaterThan(1);
    expectSortedRoster(result.created, plan);
  });

  it('reports skipped paths sorted rather than in plan-walk order', () => {
    const root = target();
    executeBootstrapPlan(
      buildBootstrapPlan({ targetRoot: root, version: '1.2.1', profile: 'tier3' }),
    );
    const plan = buildBootstrapPlan({ targetRoot: root, version: '1.2.1', profile: 'tier3' });
    const result = executeBootstrapPlan(plan);
    expect(result.skipped.length).toBeGreaterThan(1);
    expectSortedRoster(result.skipped, plan);
  });

  it('reports overwritten paths sorted rather than in plan-walk order', () => {
    const root = target();
    executeBootstrapPlan(
      buildBootstrapPlan({ targetRoot: root, version: '1.2.1', profile: 'tier3' }),
    );
    const plan = buildBootstrapPlan({ targetRoot: root, version: '1.2.1', profile: 'tier3' });
    const result = executeBootstrapPlan(plan, { force: true });
    expect(result.overwritten.length).toBeGreaterThan(1);
    expectSortedRoster(result.overwritten, plan);
  });

  it('reports preserved provenance paths sorted rather than in plan-walk order', () => {
    const root = target();
    executeBootstrapPlan(buildBootstrapPlan({ targetRoot: root, version: '1.2.1' }));
    writeFileSync(
      join(root, 'record/proofs/chain.json'),
      '{"head":"retained","records":[{"hash":"retained"}]}',
    );
    writeFileSync(join(root, '.devai/state/counters.json'), '{"TASK":7,"RGR":0,"CTG":0,"ESC":0}');
    const plan = buildBootstrapPlan({ targetRoot: root, version: '1.2.1' });
    const result = executeBootstrapPlan(plan, { force: true });
    expect(result.preserved).toEqual(['.devai/state/counters.json', 'record/proofs/chain.json']);
    expectSortedRoster(result.preserved, plan);
  });

  it('re-lays a fully zeroed allocator instead of reading it as provenance', () => {
    const root = target();
    executeBootstrapPlan(buildBootstrapPlan({ targetRoot: root, version: '1.2.1' }));
    const counters = join(root, '.devai/state/counters.json');
    writeFileSync(counters, '{"TASK":0,"RGR":0,"CTG":0,"ESC":0}');
    const result = executeBootstrapPlan(
      buildBootstrapPlan({ targetRoot: root, version: '1.2.1' }),
      { force: true },
    );
    expect(result.preserved).toEqual([]);
    expect(result.overwritten).toContain('.devai/state/counters.json');
    expect(readFileSync(counters, 'utf8')).toBe(
      `${JSON.stringify({ TASK: 0, RGR: 0, CTG: 0, ESC: 0 }, null, 2)}\n`,
    );
  });
});
// Invariants: INV-DEVAI-009
