import { existsSync, readdirSync, readFileSync } from '@devai-nyx/authority';
import { join } from 'node:path';
import type { GovernanceFinding, Builder } from './docs-governance-config-checks.js';

// ---------------------------------------------------------------------------
// Documentation information-architecture rules.
// ---------------------------------------------------------------------------

/**
 * Rule docs-ia.landing-exists — a landing page exists at the Pages root.
 * Either docs/site/docs/start/index.md OR docs/site/src/pages/index.tsx
 * satisfies the rule.
 */
export function checkDocsIaLandingExists(
  repoRoot: string,
  builder: Builder | undefined | null,
): GovernanceFinding {
  if (builder !== 'docusaurus') {
    return {
      ruleId: 'docs-ia.landing-exists',
      severity: 'pass',
      message: 'Skipped — non-Docusaurus builder',
    };
  }
  const candidates = [
    join(repoRoot, 'docs/site/docs/start/index.md'),
    join(repoRoot, 'docs/site/src/pages/index.tsx'),
    join(repoRoot, 'docs/_ia/categories.json'), // post-sync the landing emerges from start/ + categories
    join(repoRoot, 'docs/start/index.md'),
  ];
  const found = candidates.filter((p) => existsSync(p));
  if (found.length === 0) {
    return {
      ruleId: 'docs-ia.landing-exists',
      severity: 'fail',
      message:
        'No landing page found. Expected docs/start/index.md or docs/site/src/pages/index.tsx.',
      remediation:
        'Author a landing page at docs/start/index.md (or docs/site/src/pages/index.tsx). See docs/adopters/docs-layout.md#information-architecture.',
    };
  }
  return {
    ruleId: 'docs-ia.landing-exists',
    severity: 'pass',
    message: `Landing present (${found[0]?.replace(repoRoot + '/', '') ?? '?'})`,
  };
}

/**
 * Rule docs-ia.constitution-published — if law/constitution.md exists,
 * the synced site has framework/constitution.md AND a versioned_docs/version-<v>
 * snapshot for each prior version in the amendment history.
 */
export function checkDocsIaConstitutionPublished(
  repoRoot: string,
  builder: Builder | undefined | null,
): GovernanceFinding {
  if (builder !== 'docusaurus') {
    return {
      ruleId: 'docs-ia.constitution-published',
      severity: 'pass',
      message: 'Skipped — non-Docusaurus builder',
    };
  }
  const constitution = join(repoRoot, 'law/constitution.md');
  if (!existsSync(constitution)) {
    return {
      ruleId: 'docs-ia.constitution-published',
      severity: 'pass',
      message: 'No law/constitution.md — rule N/A',
    };
  }
  // Either the sync stub (source-side) or the synced output should exist.
  const stub = join(repoRoot, 'docs/reference/law.md');
  const synced = join(repoRoot, 'docs/site/docs/reference/law.md');
  if (!existsSync(stub) && !existsSync(synced)) {
    return {
      ruleId: 'docs-ia.constitution-published',
      severity: 'fail',
      message: 'Constitution exists at repo root but no Pages destination is set up.',
      remediation: 'Publish the law projection at docs/reference/law.md and run the site sync.',
    };
  }
  // versioned-docs (if present) should cover each prior version's snapshot.
  const versionsPath = join(repoRoot, 'docs/site/versions.json');
  if (existsSync(versionsPath)) {
    let versions: string[] = [];
    try {
      versions = JSON.parse(readFileSync(versionsPath, 'utf8'));
    } catch {
      /* skip */
    }
    const missingSnapshots: string[] = [];
    for (const v of versions) {
      const snapshot = join(
        repoRoot,
        `docs/site/versioned_docs/version-${v}/framework/constitution.md`,
      );
      if (!existsSync(snapshot)) missingSnapshots.push(v);
    }
    if (missingSnapshots.length > 0) {
      return {
        ruleId: 'docs-ia.constitution-published',
        severity: 'fail',
        message: `versioned_docs missing constitution snapshot for: ${missingSnapshots.join(', ')}`,
        remediation: 'Re-run docusaurus docs:version <v> for the missing version(s).',
      };
    }
  }
  return {
    ruleId: 'docs-ia.constitution-published',
    severity: 'pass',
    message: 'Constitution published per docs/adopters/docs-layout.md#information-architecture',
  };
}

/**
 * Rule docs-ia.sidebar-curated — sidebars.ts does not consist exclusively of
 * top-level autogenerated items. A hand-authored 7-section layout (or any
 * non-trivial curation) satisfies the rule.
 */
export function checkDocsIaSidebarCurated(
  repoRoot: string,
  builder: Builder | undefined | null,
): GovernanceFinding {
  if (builder !== 'docusaurus') {
    return {
      ruleId: 'docs-ia.sidebar-curated',
      severity: 'pass',
      message: 'Skipped — non-Docusaurus builder',
    };
  }
  const candidates = ['docs/site/sidebars.ts', 'docs/site/sidebars.js'];
  let content = '';
  for (const c of candidates) {
    const p = join(repoRoot, c);
    if (existsSync(p)) {
      content = readFileSync(p, 'utf8');
      break;
    }
  }
  if (content === '') {
    return {
      ruleId: 'docs-ia.sidebar-curated',
      severity: 'pass',
      message: 'No sidebars.ts/js (Docusaurus default sidebar)',
    };
  }
  // Heuristic: a curated sidebar references category labels or specific doc IDs;
  // a degenerate fully-autogenerated sidebar contains only `autogenerated` and braces.
  const hasLabels = /label:\s*['"]/.test(content);
  const hasMultipleAutogenerated = (content.match(/autogenerated/g) ?? []).length;
  if (!hasLabels && hasMultipleAutogenerated <= 1) {
    return {
      ruleId: 'docs-ia.sidebar-curated',
      severity: 'fail',
      message: 'sidebars.ts appears to be fully autogenerated with no explicit category labels.',
      remediation:
        'Author a curated sidebar with explicit `label:` fields. See docs/adopters/docs-layout.md#information-architecture.',
    };
  }
  return {
    ruleId: 'docs-ia.sidebar-curated',
    severity: 'pass',
    message: 'Sidebar carries explicit labels',
  };
}

/**
 * Rule docs-ia.framework-meta-split — law/ and docs/ exist as sibling
 * top-level categories in the current source tree.
 */
export function checkDocsIaFrameworkMetaSplit(
  repoRoot: string,
  builder: Builder | undefined | null,
): GovernanceFinding {
  if (builder !== 'docusaurus') {
    return {
      ruleId: 'docs-ia.framework-meta-split',
      severity: 'pass',
      message: 'Skipped — non-Docusaurus builder',
    };
  }
  const frameworkDir = join(repoRoot, 'law');
  const metaDir = join(repoRoot, 'docs');
  const frameworkExists = existsSync(frameworkDir);
  const metaExists = existsSync(metaDir);
  if (!frameworkExists || !metaExists) {
    const missing = [!frameworkExists ? 'law/' : null, !metaExists ? 'docs/' : null]
      .filter(Boolean)
      .join(', ');
    return {
      ruleId: 'docs-ia.framework-meta-split',
      severity: 'fail',
      message: `Law/Docs sibling split missing: ${missing}`,
      remediation: 'Create the missing law or documentation directory.',
    };
  }
  return {
    ruleId: 'docs-ia.framework-meta-split',
    severity: 'pass',
    message: 'law/ and docs/ are siblings',
  };
}

/**
 * Rule docs-ia.dashboard-current — for each dashboard page that exists under
 * §3 (framework/aspect-grid.md) or §7 (meta/self-scorecard.md, meta/test-matrix.md),
 * verify the page's last_built_at frontmatter is younger than 30 days relative
 * to its latest input file's mtime. Soft check — surfaces stale dashboards
 * without blocking.
 */
export function checkDocsIaDashboardCurrent(
  repoRoot: string,
  builder: Builder | undefined | null,
): GovernanceFinding {
  if (builder !== 'docusaurus') {
    return {
      ruleId: 'docs-ia.dashboard-current',
      severity: 'pass',
      message: 'Skipped — non-Docusaurus builder',
    };
  }
  const dashboards = [
    'docs/site/docs/theory/framework/aspect-grid.md',
    'docs/site/docs/reference/self-scorecard.md',
    'docs/site/docs/reference/test-matrix.md',
  ];
  const stale: string[] = [];
  for (const d of dashboards) {
    const path = join(repoRoot, d);
    if (!existsSync(path)) continue;
    let content = '';
    try {
      content = readFileSync(path, 'utf8');
    } catch {
      continue;
    }
    const m = content.match(/last_built_at:\s*(\S+)/);
    if (!m || m[1] === undefined) continue; // no frontmatter; skip silently
    const ts = Date.parse(m[1]);
    if (Number.isNaN(ts)) continue;
    const ageMs = Date.now() - ts;
    const ageDays = ageMs / (1000 * 60 * 60 * 24);
    if (ageDays > 30) stale.push(`${d} (${Math.floor(ageDays)} days old)`);
  }
  if (stale.length > 0) {
    return {
      ruleId: 'docs-ia.dashboard-current',
      severity: 'warn',
      message: `Dashboards older than 30 days: ${stale.join('; ')}`,
      remediation:
        'Run npm run sync-docs to refresh build-frozen dashboards before publication. See docs/adopters/docs-layout.md#information-architecture.',
    };
  }
  return {
    ruleId: 'docs-ia.dashboard-current',
    severity: 'pass',
    message: 'Dashboards current (or absent)',
  };
}

/**
 * Rule docs-ia.workflow-page-set (ADR-GOV-0021) — every file under .github/workflows/ has one
 * reference page docs/dev/operations/workflows/<stem>.md and every page (README.md is the index)
 * has its workflow file. Repositories without either directory are out of scope.
 */
export function checkDocsIaWorkflowPageSet(repoRoot: string): GovernanceFinding {
  const ruleId = 'docs-ia.workflow-page-set';
  const workflowsDir = join(repoRoot, '.github/workflows');
  const pagesDir = join(repoRoot, 'docs/dev/operations/workflows');
  if (!existsSync(workflowsDir) && !existsSync(pagesDir)) {
    return { ruleId, severity: 'pass', message: 'Skipped — no workflows or workflow pages' };
  }
  const stems = (dir: string, pattern: RegExp): string[] =>
    existsSync(dir)
      ? readdirSync(dir)
          .filter((name) => pattern.test(name) && name !== 'README.md')
          .map((name) => name.replace(pattern, ''))
          .sort()
      : [];
  const workflows = stems(workflowsDir, /\.ya?ml$/u);
  const pages = stems(pagesDir, /\.md$/u);
  const problems = [
    ...workflows
      .filter((stem) => !pages.includes(stem))
      .map(
        (stem) =>
          `DOCS_WORKFLOW_PAGE_MISSING: .github/workflows/${stem} has no page docs/dev/operations/workflows/${stem}.md`,
      ),
    ...pages
      .filter((stem) => !workflows.includes(stem))
      .map(
        (stem) =>
          `DOCS_WORKFLOW_PAGE_MISSING: docs/dev/operations/workflows/${stem}.md has no workflow file .github/workflows/${stem}.yml`,
      ),
  ];
  if (problems.length > 0) {
    return {
      ruleId,
      severity: 'fail',
      message: problems.join('; '),
      remediation:
        'Add or remove the page docs/dev/operations/workflows/<stem>.md so it pairs one to one with .github/workflows/<stem>.yml.',
    };
  }
  return {
    ruleId,
    severity: 'pass',
    message: `Workflow page set complete (${workflows.length} workflows)`,
  };
}
