/**
 * Deterministic generator for the adopter's tracking reconciliation workflow.
 *
 * The workflow is a safety-critical artifact, so every property that makes it
 * safe is derived from the canonical policy rather than written by hand:
 *
 *  - `push` on the trusted default branch and explicit `workflow_dispatch`
 *    only. `pull_request_target` is never emitted; it would run credentialed
 *    code against an untrusted ref.
 *  - `contents: read` and `issues: write` and nothing else. There is no PAT,
 *    package-token, or broader-permission fallback.
 *  - Actions pinned to immutable commit SHAs, never to tags or branches.
 *  - A per-round concurrency group, so two reconciliations of one round cannot
 *    interleave and duplicate a comment.
 *  - Reconciliation only. It replays batches an Owner already authorized and
 *    is never a required readiness context, so a projection failure is visible
 *    without touching a governed verdict.
 *
 * Generation is a pure function of the policy: two independent runs produce
 * identical bytes, which is what makes the bound workflow digest meaningful.
 */
import { canonicalSha256 } from '@devai-nyx/utils';
import type { TrackingPolicyDefaults } from './config.js';

export function trackingWorkflowDigest(workflow: string): string {
  return canonicalSha256({ workflow });
}

export function renderTrackingWorkflow(defaults: TrackingPolicyDefaults): string {
  const { workflow } = defaults;
  const branch = workflow.trusted_ref.replace(/^refs\/heads\//u, '');
  const lines = [
    '# @generated by devai init bind --tracking-adapter github-issues',
    '# Do not edit. Regenerate with the same command; drift fails devai doctor.',
    'name: DEVAI governance tracking',
    '',
    'on:',
    '  push:',
    '    branches:',
    `      - ${branch}`,
    '  workflow_dispatch:',
    '    inputs:',
    '      round:',
    '        description: Governed round to reconcile (for example R-0042)',
    '        required: true',
    '        type: string',
    '',
    '# Output-only projection. Issue comments, labels, and edits are untrusted',
    '# state and can never authorize, route, close, merge, or publish anything.',
    'permissions:',
    `  contents: ${workflow.permissions.contents}`,
    `  issues: ${workflow.permissions.issues}`,
    '',
    'concurrency:',
    `  group: ${workflow.concurrency_group_prefix}-\${{ github.event.inputs.round || github.ref }}`,
    '  cancel-in-progress: false',
    '',
    'jobs:',
    '  reconcile:',
    '    name: Reconcile sealed governance batches',
    `    if: github.ref == '${workflow.trusted_ref}'`,
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - name: Check out the trusted ref',
    `        uses: actions/checkout@${workflow.pinned_actions.checkout}`,
    '        with:',
    '          persist-credentials: false',
    '      - name: Set up Node',
    `        uses: actions/setup-node@${workflow.pinned_actions.setup_node}`,
    '        with:',
    "          node-version: '24'",
    '      - name: Install the adopter toolchain',
    '        run: |',
    '          corepack enable',
    '          pnpm install --frozen-lockfile',
    '      - name: Report the sealed projection outbox',
    "        if: github.event.inputs.round != ''",
    '        env:',
    '          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}',
    '          DEVAI_TRACKING_ROUND: ${{ github.event.inputs.round }}',
    '        # Reconcile-only and read-only. It reports what an Owner-authorized',
    '        # sync would project; it never creates an activation, never recreates',
    '        # a missing issue, and never writes without a declared Owner subject.',
    '        run: |',
    '          pnpm exec devai round tracking sync \\',
    '            --round "${DEVAI_TRACKING_ROUND}" \\',
    '            --reconcile \\',
    '            --format json',
    '      - name: Report projection health without gating readiness',
    '        if: always()',
    '        run: |',
    '          echo "Tracking projection is best-effort and is not a required check." \\',
    '            >> "${GITHUB_STEP_SUMMARY}"',
    '',
  ];
  return lines.join('\n');
}
