import {
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  realpathSync,
  runAuthorityHostEffectsWithRollback,
  writeFileSync,
} from '@devai-nyx/authority';
import { createHash } from 'node:crypto';
import { dirname, join, relative, resolve, sep } from 'node:path';
import type { CAC } from 'cac';
import {
  buildConstitutionBindingPlan,
  reconcileProjectConfig,
  resolveCanonicalConstitution,
  resolveCanonicalPolicyContent,
  verifyConstitutionBinding,
} from '@devai-nyx/skills';
import { validators } from '@devai-nyx/schemas';
import { EXIT_FAIL, EXIT_GATE, EXIT_PASS, EXIT_PRECONDITION, EXIT_REVIEW } from '@devai-nyx/utils';
import { defineCommand } from '../../define-command.js';
import { cliError, renderCliError } from '../../cli-error.js';
import { executeAuthorityPolicyMaterialization } from '../../authority/command-capabilities.js';
import { resolveCliVersion } from '../../version.js';
import {
  ATTESTED_RC_WORKFLOW_FILE,
  LEDGER_WORKFLOW_FILE,
  attestedRcVerificationWorkflow,
  buildCiScaffoldPlan,
  executeCiScaffoldPlan,
  ledgerVerificationWorkflow,
} from '../../services/ci-scaffold/index.js';
import {
  buildGithubActionsAdapterPlan,
  executeGithubActionsAdapterPlan,
  verifyGithubActionsAdapter,
  type GithubActionsAdapterPlan,
} from '../../services/github-actions-adapter/index.js';
import {
  buildHooksInstallPlan,
  executeHooksInstallPlan,
  preflightHooksInstallPlan,
  verifyInstalledPostMergeAdapter,
} from '../../services/hooks-install/index.js';
import { isJsonObject, jsonBytes, type JsonObject } from '../../services/adopter-policy.js';
import { parseAdopterPolicyBinding } from '../../services/adopter-policy-binding.js';
import {
  compareVersions,
  loadAdopterMigrations,
  releasesInRange,
  type MigrationChange,
  type ObligationCheck,
  type UpgradeSegment,
} from '../../services/adopter-migrations.js';
import { checkPolicyMaterializationCurrent } from '../doctor-policy-checks.js';
import { checkAuthorityEnforcement } from '../doctor-install-checks.js';
import { checkConstitutionBinding } from '../doctor-environment-checks.js';
import type { CheckResult } from '../doctor-support.js';
import {
  ADOPTER_POLICY_RECEIPT,
  BIND_JOURNAL_PATHS,
  UPGRADE_RECEIPT,
  planAdopterPolicyBind,
  recordAuthorityExtension,
  recoverInterruptedAdopterPolicyBind,
  resolveAdopterPolicySource,
  writeAdopterPolicyPairAtomically,
} from './bind-adapters.js';
import { DEFAULT_REPO_ROOT, emit } from './shared.js';

const PROJECT = '.devai/config/project.json';
const PIN = '.devai/pin/constitution.md';
const POINTER = '.devai/constitution.md';
const AUTHORITY_POLICY = '.devai/config/authority-policy.json';
const GITHUB_ACTIONS_CONFIG = '.devai/config/github-actions-host-adapter.json';
const POST_MERGE_CONFIG = '.devai/config/post-merge-host-adapter.json';
const TRACKING_CONFIG = '.devai/config/github-issues-tracking.json';
const BIND_JOURNAL = '.devai/config/adopter-policy-binding.journal.json';
const OPERATIONAL_LAW = [
  'domains.json',
  'forbidden-actions.json',
  'glob-guards.json',
  'scorecard-na.json',
  'thresholds.json',
] as const;
const POINTER_STAMP = /Generated by DEVAI v([0-9A-Za-z.+-]+)\.\n?$/u;
const FRAMEWORK_POLICY_ID = 'devai.devai-adoption';
/** The doctor checks an upgrade must leave passing before it reports success (#264). */
const POSTCHECKS = [
  'policy-materialization-current',
  'authority-enforcement',
  'constitution-binding',
];

export interface InitUpgradeOptions {
  readonly target?: string;
  readonly constitution?: boolean;
  readonly write?: boolean;
  readonly human?: boolean;
}

type ChangeSegment = UpgradeSegment | 'version-stamp';

export interface UpgradeFileChange {
  readonly path: string;
  readonly operation: 'create' | 'update';
  readonly segment: ChangeSegment;
}

export interface UpgradeRefusal {
  readonly code: string;
  readonly message: string;
  readonly key?: string;
  readonly pointer?: string;
}

export interface UpgradeObligation {
  readonly change: string;
  readonly check: ObligationCheck;
  readonly requirement: string;
  readonly status: 'satisfied' | 'satisfied-by-upgrade' | 'pending';
}

export interface UpgradeStaleStamp {
  readonly path: string;
  readonly field: string;
  readonly version: string;
  readonly refreshed: boolean;
}

export interface UpgradePlan {
  readonly from: string;
  readonly to: string;
  readonly status: 'ready' | 'no-op' | 'refused';
  readonly constitution: {
    readonly bound: string | null;
    readonly installed: string;
    readonly rebind_requested: boolean;
  };
  readonly releases: readonly {
    readonly version: string;
    readonly status: string;
    readonly changes: readonly Pick<
      MigrationChange,
      'id' | 'kind' | 'summary' | 'decision_records' | 'segments'
    >[];
  }[];
  readonly segments: readonly { readonly segment: UpgradeSegment; readonly run: boolean }[];
  readonly changed_files: readonly UpgradeFileChange[];
  readonly retired_keys: readonly string[];
  readonly replaced_defaults: readonly {
    readonly change: string;
    readonly source: string;
    readonly source_key: string;
    readonly policy: string;
    readonly missing: readonly string[];
  }[];
  readonly stale_version_stamps: readonly UpgradeStaleStamp[];
  readonly obligations: readonly UpgradeObligation[];
  readonly refusals: readonly UpgradeRefusal[];
  readonly interrupted_bind: boolean;
}

interface PreparedUpgrade {
  readonly plan: UpgradePlan;
  /** Final bytes for paths outside the bind journal (constitution pin and pointer). */
  readonly direct: ReadonlyMap<string, string>;
  /** Final bytes landed through the bind journal as one atomic set. */
  readonly journaled: ReadonlyMap<string, string>;
  readonly adopterReceipt?: Readonly<Record<string, unknown>>;
  readonly adopterExtension?: Parameters<typeof recordAuthorityExtension>[2];
  readonly githubActions?: GithubActionsAdapterPlan;
  readonly postMerge?: ReturnType<typeof buildHooksInstallPlan>;
  readonly ci: boolean;
}

/** A precondition that stops the upgrade before any plan is computed or byte written. */
class UpgradePrecondition extends Error {
  readonly code: string;
  readonly remediation: string;
  readonly context: Readonly<Record<string, unknown>>;

  constructor(
    code: string,
    message: string,
    remediation: string,
    context: Readonly<Record<string, unknown>> = {},
  ) {
    super(message);
    this.code = code;
    this.remediation = remediation;
    this.context = context;
  }
}

/** The post-check found a failing doctor check; every write of the upgrade is rolled back. */
class UpgradePostcheckFailure extends Error {
  readonly checks: readonly CheckResult[];

  constructor(checks: readonly CheckResult[]) {
    super(
      `INIT_UPGRADE_POSTCHECK_FAILED:${checks
        .filter((check) => !check.ok)
        .map((check) => check.name)
        .join(',')}`,
    );
    this.checks = checks;
  }
}

function sha256(value: string | Buffer): string {
  return createHash('sha256').update(value).digest('hex');
}

function readTextIfPresent(path: string): string | null {
  return existsSync(path) ? readFileSync(path, 'utf8') : null;
}

function readJsonObject(path: string): JsonObject | undefined {
  try {
    const parsed: unknown = JSON.parse(readFileSync(path, 'utf8'));
    return isJsonObject(parsed) ? parsed : undefined;
  } catch {
    return undefined;
  }
}

function stampAt(document: JsonObject | undefined, path: readonly string[]): string | undefined {
  let cursor: unknown = document;
  for (const key of path) {
    if (!isJsonObject(cursor)) return undefined;
    cursor = cursor[key];
  }
  return typeof cursor === 'string' ? cursor : undefined;
}

/** `/ci_economy/attested_rc` is reported to the adopter as `ci_economy.attested_rc`. */
function pointerKey(pointer: string): string {
  return pointer.split('/').slice(1).join('.');
}

function declaresItem(declared: unknown, item: string): boolean {
  if (isJsonObject(declared) && Array.isArray(declared['cells'])) {
    return declared['cells'].some((cell) => isJsonObject(cell) && cell['cell'] === item);
  }
  return JSON.stringify(declared).includes(JSON.stringify(item));
}

function hasProofLines(targetRoot: string): boolean {
  const work = join(targetRoot, 'record/proofs/work');
  return existsSync(work) && lstatSync(work).isDirectory();
}

/**
 * Compute the whole upgrade from the bound devai_version to the installed version without
 * writing: the manifest entries in range, the final bytes of every bind segment composed in
 * canonical order, the changed files, the owned keys a rebind would retire, the declarations
 * that replace a changed default, the stale version stamps, and the obligations.
 */
export function prepareAdopterUpgrade(
  targetRoot: string,
  installed: string,
  requestConstitution: boolean,
): PreparedUpgrade {
  const projectPath = join(targetRoot, PROJECT);
  if (!existsSync(projectPath)) {
    throw new UpgradePrecondition(
      'INIT_UPGRADE_PROJECT_CONFIG_MISSING',
      `${PROJECT} is absent`,
      'Bind the repository first: devai init bind --full --target . --tier <tier> --as-role architect --write',
    );
  }
  const currentProject = readJsonObject(projectPath);
  if (currentProject === undefined) {
    throw new UpgradePrecondition(
      'INIT_UPGRADE_PROJECT_CONFIG_INVALID',
      `${PROJECT} is not a JSON object`,
      `Restore ${PROJECT} from version control and retry.`,
    );
  }
  const from = stampAt(currentProject, ['devai_version']);
  if (from === undefined) {
    throw new UpgradePrecondition(
      'INIT_UPGRADE_FROM_VERSION_MISSING',
      `${PROJECT} carries no devai_version`,
      'Bind the repository with init bind before upgrading it.',
    );
  }
  const manifest = loadAdopterMigrations();
  if (compareVersions(from, manifest.baseline) < 0) {
    throw new UpgradePrecondition(
      'INIT_UPGRADE_FROM_VERSION_UNSUPPORTED',
      `bound version ${from} is below the manifest baseline ${manifest.baseline}`,
      `Upgrade to ${manifest.baseline} with the init bind segments first, then run init upgrade.`,
      { from, baseline: manifest.baseline },
    );
  }
  if (compareVersions(from, installed) > 0) {
    throw new UpgradePrecondition(
      'INIT_UPGRADE_DOWNGRADE_REFUSED',
      `bound version ${from} is newer than the installed ${installed}`,
      `Install @aarusso-nyx/devai@${from} or newer.`,
      { from, to: installed },
    );
  }
  const canonical = resolveCanonicalConstitution();
  if (canonical === null || canonical.version === null) {
    throw new UpgradePrecondition(
      'INIT_UPGRADE_CONSTITUTION_UNAVAILABLE',
      'no installed constitution version could be resolved',
      'Reinstall @aarusso-nyx/devai and retry.',
    );
  }
  const releases = releasesInRange(manifest, from, installed);
  const changes = releases.flatMap((release) => release.changes);
  const refusals: UpgradeRefusal[] = [];
  const stale: UpgradeStaleStamp[] = [];
  const replaced: UpgradePlan['replaced_defaults'][number][] = [];
  const finalBytes = new Map<string, { readonly bytes: string; readonly segment: ChangeSegment }>();
  const set = (path: string, bytes: string, segment: ChangeSegment): void => {
    finalBytes.set(path, { bytes, segment });
  };

  // constitution (only when requested: adopting a constitution is an Architect decision)
  const boundConstitution = verifyConstitutionBinding(targetRoot).pin?.version ?? null;
  let project: JsonObject = currentProject;
  if (requestConstitution) {
    set(PIN, canonical.text, 'constitution');
    project = reconcileProjectConfig(project, {
      version: installed,
      constitution: { version: canonical.version, sha256: canonical.sha256 },
    });
  }
  const pointerPath = join(targetRoot, POINTER);
  if (existsSync(pointerPath) && lstatSync(pointerPath).isFile()) {
    const stamp = POINTER_STAMP.exec(readFileSync(pointerPath, 'utf8'))?.[1];
    if (stamp !== undefined && stamp !== installed) {
      stale.push({ path: POINTER, field: 'generated-by', version: stamp, refreshed: true });
      set(
        POINTER,
        buildConstitutionBindingPlan(targetRoot, installed).pointerFile.content,
        'constitution',
      );
    }
  } else if (!existsSync(pointerPath) && requestConstitution) {
    set(
      POINTER,
      buildConstitutionBindingPlan(targetRoot, installed).pointerFile.content,
      'constitution',
    );
  }

  // operational law and subprocess effects: byte-identical package materializations
  for (const file of OPERATIONAL_LAW) {
    set(`.devai/config/${file}`, resolveCanonicalPolicyContent(file), 'operational-law');
  }
  const subprocess = resolveCanonicalPolicyContent('subprocess-effects.json');
  if (!validators.subprocessEffects(JSON.parse(subprocess) as unknown)) {
    throw new UpgradePrecondition(
      'INIT_UPGRADE_SUBPROCESS_EFFECTS_INVALID',
      'the installed subprocess-effects policy fails its schema',
      'Reinstall @aarusso-nyx/devai and retry.',
    );
  }
  set('.devai/config/subprocess-effects.json', subprocess, 'subprocess-effects');

  // adopter policy: re-projected after operational law, over the post-constitution project
  const receiptPath = join(targetRoot, ADOPTER_POLICY_RECEIPT);
  let adopterReceipt: Readonly<Record<string, unknown>> | undefined;
  let adopterExtension: PreparedUpgrade['adopterExtension'];
  let retiredKeys: readonly string[] = [];
  let receiptPolicyId: string | undefined;
  if (existsSync(receiptPath)) {
    const parsed = parseAdopterPolicyBinding(readFileSync(receiptPath, 'utf8'));
    if ('reason' in parsed) {
      throw new UpgradePrecondition(
        'INIT_UPGRADE_ADOPTER_RECEIPT_INVALID',
        `${ADOPTER_POLICY_RECEIPT} is unreadable (${parsed.reason})`,
        'Rebind the adopter policy with init bind --adopter-policy <source> --as-role architect --write.',
      );
    }
    receiptPolicyId = parsed.binding.policy_id;
    const source = parsed.binding.source_path;
    const sourcePath = resolveAdopterPolicySource(targetRoot, source);
    const policy = readJsonObject(sourcePath) ?? {};
    const bind = planAdopterPolicyBind(targetRoot, sourcePath, {
      currentProject: project,
      frameworkVersion: installed,
      ...(requestConstitution && { constitutionVersion: canonical.version }),
    });
    for (const [path, bytes] of bind.resolved) set(path, bytes, 'adopter-policy');
    project = JSON.parse(bind.resolved.get(PROJECT) ?? jsonBytes(project)) as JsonObject;
    retiredKeys = bind.retiredKeys;
    for (const pointer of retiredKeys) {
      refusals.push({
        code: 'INIT_UPGRADE_RETIREMENT_UNDECLARED',
        key: pointerKey(pointer),
        pointer,
        message: `rebinding ${source} would retire the project.json key ${pointerKey(pointer)}, which the source does not declare`,
      });
    }
    const plannedReceipt = bind.writes.get(ADOPTER_POLICY_RECEIPT);
    if (plannedReceipt !== undefined) {
      // A receipt that already carries the authority extension this bind will record again
      // stands as it is; recordAuthorityExtension rewrites it only when the bytes move.
      const current = readJsonObject(receiptPath);
      const standing =
        current !== undefined &&
        current['authority_extension'] !== undefined &&
        readTextIfPresent(receiptPath) ===
          jsonBytes({
            ...bind.receipt,
            retired_keys: current['retired_keys'],
            authority_extension: current['authority_extension'],
          });
      if (!standing) set(ADOPTER_POLICY_RECEIPT, plannedReceipt, 'adopter-policy');
    }
    adopterReceipt = bind.receipt;
    adopterExtension = bind.authorityExtension;
    for (const change of changes) {
      if (change.kind !== 'changed-default' || change.default === undefined) continue;
      const declared = policy[change.default.source_key];
      if (declared === undefined) continue;
      const missing = change.default.added.filter((item) => !declaresItem(declared, item));
      if (missing.length > 0) {
        replaced.push({
          change: change.id,
          source,
          source_key: change.default.source_key,
          policy: change.default.policy,
          missing,
        });
      }
    }
  } else {
    project = reconcileProjectConfig(project, { version: installed });
    set(PROJECT, jsonBytes(project), requestConstitution ? 'constitution' : 'version-stamp');
  }
  if (from !== installed) {
    stale.push({ path: PROJECT, field: 'devai_version', version: from, refreshed: true });
  }

  const direct = new Map<string, string>();
  const journaled = new Map<string, string>();
  const changed: UpgradeFileChange[] = [];
  for (const [path, { bytes, segment }] of finalBytes) {
    const current = readTextIfPresent(join(targetRoot, path));
    if (current === bytes) continue;
    changed.push({ path, operation: current === null ? 'create' : 'update', segment });
    (BIND_JOURNAL_PATHS.includes(path) ? journaled : direct).set(path, bytes);
  }

  // host adapters: a stale or unverifiable adapter is rebound at the installed version
  let githubActions: GithubActionsAdapterPlan | undefined;
  if (existsSync(join(targetRoot, GITHUB_ACTIONS_CONFIG))) {
    const config = readJsonObject(join(targetRoot, GITHUB_ACTIONS_CONFIG));
    const stamp = stampAt(config, ['package_binding', 'version']) ?? 'missing';
    const verification = verifyGithubActionsAdapter(targetRoot, installed);
    if (stamp !== installed) {
      stale.push({
        path: GITHUB_ACTIONS_CONFIG,
        field: 'package_binding.version',
        version: stamp,
        refreshed: true,
      });
    }
    if (!verification.ok) {
      githubActions = buildGithubActionsAdapterPlan(targetRoot, installed);
      for (const [path, bytes] of [
        [githubActions.workflowPath, githubActions.workflowBytes],
        [githubActions.configPath, githubActions.configBytes],
      ] as const) {
        const current = readTextIfPresent(path);
        if (current === bytes) continue;
        changed.push({
          path: relative(targetRoot, path).split(sep).join('/'),
          operation: current === null ? 'create' : 'update',
          segment: 'host-adapters',
        });
      }
    }
  }

  // authority policy: rematerialized when any bound input moves or it no longer matches
  const authority = checkAuthorityEnforcement(targetRoot);
  const authorityCurrent = authority.info?.['policy_binding'] === 'current';
  if (!existsSync(join(targetRoot, AUTHORITY_POLICY))) {
    changed.push({ path: AUTHORITY_POLICY, operation: 'create', segment: 'authority' });
  } else if (!authorityCurrent || changed.length > 0) {
    changed.push({ path: AUTHORITY_POLICY, operation: 'update', segment: 'authority' });
  }

  // the post-merge attestation binds the authority policy digest, so it moves with it
  let postMerge: PreparedUpgrade['postMerge'];
  if (existsSync(join(targetRoot, POST_MERGE_CONFIG))) {
    const config = readJsonObject(join(targetRoot, POST_MERGE_CONFIG));
    const stamp = stampAt(config, ['package_binding', 'version']) ?? 'missing';
    if (stamp !== installed) {
      stale.push({
        path: POST_MERGE_CONFIG,
        field: 'package_binding.version',
        version: stamp,
        refreshed: true,
      });
    }
    const verification = verifyInstalledPostMergeAdapter(targetRoot, installed);
    if (
      stamp !== installed ||
      !verification.ok ||
      changed.some((entry) => entry.path === AUTHORITY_POLICY)
    ) {
      postMerge = buildHooksInstallPlan({
        targetRoot,
        hook: 'post-merge',
        devaiVersion: installed,
      });
      changed.push({ path: POST_MERGE_CONFIG, operation: 'update', segment: 'host-adapters' });
    }
  }

  // harness ci: the byte-compared verifier workflow the bound project.json selects
  const economy = isJsonObject(project['ci_economy']) ? project['ci_economy'] : undefined;
  const attested = economy?.['attested_rc'] !== undefined;
  const ledgerRelative = `.github/workflows/${LEDGER_WORKFLOW_FILE}`;
  const ciTarget = attested
    ? {
        path: `.github/workflows/${ATTESTED_RC_WORKFLOW_FILE}`,
        bytes: attestedRcVerificationWorkflow(),
      }
    : existsSync(join(targetRoot, ledgerRelative))
      ? { path: ledgerRelative, bytes: ledgerVerificationWorkflow() }
      : undefined;
  let ci = false;
  if (ciTarget !== undefined) {
    const current = readTextIfPresent(join(targetRoot, ciTarget.path));
    if (current !== ciTarget.bytes) {
      ci = true;
      changed.push({
        path: ciTarget.path,
        operation: current === null ? 'create' : 'update',
        segment: 'harness-ci',
      });
    }
  }

  // stamps the upgrade reports but does not refresh: rebinding tracking is its own decision
  const tracking = readJsonObject(join(targetRoot, TRACKING_CONFIG));
  const trackingStamp = stampAt(tracking, ['binding', 'package_version']);
  if (trackingStamp !== undefined && trackingStamp !== installed) {
    stale.push({
      path: TRACKING_CONFIG,
      field: 'binding.package_version',
      version: trackingStamp,
      refreshed: false,
    });
  }

  const currentThresholds = readJsonObject(join(targetRoot, '.devai/config/thresholds.json'));
  const finalThresholds = JSON.parse(
    finalBytes.get('.devai/config/thresholds.json')?.bytes ?? '{}',
  ) as JsonObject;
  const obligations: UpgradeObligation[] = changes.flatMap((change) => {
    if (change.obligation === undefined) return [];
    const { check, requirement } = change.obligation;
    let status: UpgradeObligation['status'];
    if (check === 'thresholds-soft-gate') {
      status =
        currentThresholds?.['soft_gate'] !== undefined
          ? 'satisfied'
          : finalThresholds['soft_gate'] !== undefined
            ? 'satisfied-by-upgrade'
            : 'pending';
    } else if (check === 'constitution-version') {
      const target = change.constitution?.to ?? canonical.version ?? '';
      status =
        boundConstitution !== null && compareVersions(boundConstitution, target) >= 0
          ? 'satisfied'
          : requestConstitution
            ? 'satisfied-by-upgrade'
            : 'pending';
    } else if (check === 'proof-anchor-baseline') {
      status =
        !hasProofLines(targetRoot) ||
        existsSync(join(targetRoot, 'record/proofs/anchor-baseline.json'))
          ? 'satisfied'
          : 'pending';
    } else {
      status =
        receiptPolicyId !== undefined && receiptPolicyId !== FRAMEWORK_POLICY_ID
          ? 'satisfied'
          : 'pending';
    }
    return [{ change: change.id, check, requirement, status }];
  });

  const ran = new Set(changed.map((entry) => entry.segment));
  const status: UpgradePlan['status'] =
    refusals.length > 0
      ? 'refused'
      : from === installed && changed.length === 0
        ? 'no-op'
        : 'ready';
  const plan: UpgradePlan = {
    from,
    to: installed,
    status,
    constitution: {
      bound: boundConstitution,
      installed: canonical.version,
      rebind_requested: requestConstitution,
    },
    releases: releases.map((release) => ({
      version: release.version,
      status: release.status,
      changes: release.changes.map(({ id, kind, summary, decision_records, segments }) => ({
        id,
        kind,
        summary,
        decision_records,
        segments,
      })),
    })),
    segments: manifest.segments.map((segment) => ({ segment, run: ran.has(segment) })),
    changed_files: changed,
    retired_keys: retiredKeys,
    replaced_defaults: replaced,
    stale_version_stamps: stale,
    obligations,
    refusals,
    interrupted_bind: existsSync(join(targetRoot, BIND_JOURNAL)),
  };
  return {
    plan,
    direct,
    journaled,
    ...(adopterReceipt !== undefined && { adopterReceipt }),
    ...(adopterExtension !== undefined && { adopterExtension }),
    ...(githubActions !== undefined && { githubActions }),
    ...(postMerge !== undefined && { postMerge }),
    ci,
  };
}

/**
 * Land a prepared upgrade: the bind segments in canonical order inside one rollback scope,
 * the configuration set through the bind journal, then the doctor post-checks. A failing
 * post-check restores every byte the upgrade wrote; success records the upgrade receipt.
 */
function applyAdopterUpgrade(targetRoot: string, prepared: PreparedUpgrade) {
  const absolute = (path: string) => join(targetRoot, path);
  const targets = [
    ...[...prepared.direct.keys(), ...prepared.journaled.keys()].map(absolute),
    absolute(AUTHORITY_POLICY),
    absolute(ADOPTER_POLICY_RECEIPT),
    absolute(UPGRADE_RECEIPT),
    ...(prepared.githubActions === undefined
      ? []
      : [prepared.githubActions.workflowPath, prepared.githubActions.configPath]),
    ...(prepared.postMerge === undefined ? [] : preflightHooksInstallPlan(prepared.postMerge)),
    ...(prepared.ci
      ? [
          absolute(`.github/workflows/${LEDGER_WORKFLOW_FILE}`),
          absolute(`.github/workflows/${ATTESTED_RC_WORKFLOW_FILE}`),
        ]
      : []),
  ];
  return runAuthorityHostEffectsWithRollback(targets, () => {
    for (const [path, bytes] of prepared.direct) {
      mkdirSync(dirname(absolute(path)), { recursive: true });
      writeFileSync(absolute(path), bytes);
    }
    if (prepared.journaled.size > 0)
      writeAdopterPolicyPairAtomically(targetRoot, prepared.journaled);
    let authority = executeAuthorityPolicyMaterialization();
    if (prepared.adopterReceipt !== undefined) {
      recordAuthorityExtension(targetRoot, prepared.adopterReceipt, prepared.adopterExtension);
    }
    if (prepared.githubActions !== undefined) {
      executeGithubActionsAdapterPlan(prepared.githubActions);
      const verification = verifyGithubActionsAdapter(targetRoot, prepared.plan.to);
      if (!verification.ok) {
        throw new Error(`GITHUB_ACTIONS_ADAPTER_INVALID:${verification.errors.join(',')}`);
      }
      authority = executeAuthorityPolicyMaterialization();
    }
    if (prepared.postMerge !== undefined) {
      executeHooksInstallPlan(prepared.postMerge);
      const verification = verifyInstalledPostMergeAdapter(targetRoot, prepared.plan.to);
      if (!verification.ok) {
        throw new Error(`POST_MERGE_ADAPTER_INVALID:${verification.errors.join(',')}`);
      }
    }
    if (prepared.ci) {
      const ciPlan = buildCiScaffoldPlan({ targetRoot });
      if (readTextIfPresent(ciPlan.path) !== ciPlan.content) {
        executeCiScaffoldPlan(ciPlan, { force: true });
      }
    }
    const checks = [
      checkPolicyMaterializationCurrent(targetRoot),
      checkAuthorityEnforcement(targetRoot),
      checkConstitutionBinding(targetRoot),
    ];
    if (checks.some((check) => !check.ok)) throw new UpgradePostcheckFailure(checks);
    const changedFiles = prepared.plan.changed_files.map((entry) => {
      const bytes = existsSync(absolute(entry.path))
        ? readFileSync(absolute(entry.path))
        : undefined;
      return { ...entry, ...(bytes !== undefined && { sha256: sha256(bytes) }) };
    });
    const receipt = {
      schemaVersion: '1.0.0',
      from: prepared.plan.from,
      to: prepared.plan.to,
      upgraded_at: new Date().toISOString(),
      constitution: {
        from: prepared.plan.constitution.bound,
        to: prepared.plan.constitution.rebind_requested
          ? prepared.plan.constitution.installed
          : prepared.plan.constitution.bound,
      },
      migrations: prepared.plan.releases.flatMap((release) =>
        release.changes.map((change) => change.id),
      ),
      retired_keys: prepared.plan.retired_keys,
      changed_files: changedFiles,
      stale_version_stamps: prepared.plan.stale_version_stamps,
      obligations: prepared.plan.obligations.map(({ change, check, status }) => ({
        change,
        check,
        status,
      })),
      postchecks: checks.map((check) => ({ name: check.name, ok: check.ok })),
    };
    writeAdopterPolicyPairAtomically(targetRoot, new Map([[UPGRADE_RECEIPT, jsonBytes(receipt)]]));
    return { receipt, authority_policy: authority };
  });
}

function refuse(error: UpgradePrecondition, human: boolean): void {
  process.stderr.write(
    renderCliError(
      cliError({
        code: error.code,
        class: 'precondition',
        exit: 5,
        message: error.message,
        remediation: error.remediation,
        context: error.context,
      }),
      !human,
    ),
  );
  process.exitCode = EXIT_PRECONDITION;
}

function humanPlan(plan: UpgradePlan): string {
  const lines = [
    `init upgrade: ${plan.from} -> ${plan.to} (${plan.status})`,
    ...plan.releases.map(
      (release) => `  ${release.version}: ${release.changes.map((change) => change.id).join(', ')}`,
    ),
    ...plan.changed_files.map((entry) => `  ${entry.operation} ${entry.path} [${entry.segment}]`),
    ...plan.stale_version_stamps.map(
      (stamp) =>
        `  stale ${stamp.path} ${stamp.field}=${stamp.version}${stamp.refreshed ? '' : ' (not refreshed)'}`,
    ),
    ...plan.replaced_defaults.map(
      (entry) =>
        `  ${entry.source} ${entry.source_key} replaces the default and omits ${entry.missing.join(', ')}`,
    ),
    ...plan.obligations.map((entry) => `  obligation ${entry.change}: ${entry.status}`),
    ...plan.refusals.map((entry) => `  refused ${entry.code}: ${entry.message}`),
  ];
  return lines.join('\n');
}

/** The adopter upgrade command (#264): plan by default, apply with --write. */
export const initUpgrade = defineCommand({
  name: 'init upgrade',
  description:
    'Plan or apply the move of an adopter repository from its bound DEVAI version to the installed one.',
  authority: 'mesh_controller',
  register(cli: CAC): void {
    cli
      .command(
        'init-upgrade',
        'Plan the adopter upgrade to the installed version (apply with --write)',
      )
      .option('--target <path>', `Target directory (default: ${DEFAULT_REPO_ROOT})`)
      .option('--constitution', 'Also bind the installed Constitution text and digest pin.')
      .option('--write', 'Apply the planned upgrade; without it the command only plans.')
      .option('--human', 'Human-readable output')
      .action((options: InitUpgradeOptions) => {
        const human = options.human === true;
        try {
          const targetRoot = realpathSync(resolve(options.target ?? DEFAULT_REPO_ROOT));
          const installed = resolveCliVersion();
          const constitution = options.constitution === true;
          if (options.write !== true) {
            const { plan } = prepareAdopterUpgrade(targetRoot, installed, constitution);
            emit({ plan }, human, humanPlan(plan));
            process.exitCode = plan.status === 'refused' ? EXIT_REVIEW : EXIT_PASS;
            return;
          }
          const recovered = recoverInterruptedAdopterPolicyBind(targetRoot);
          const prepared = prepareAdopterUpgrade(targetRoot, installed, constitution);
          const { plan } = prepared;
          if (plan.status === 'refused') {
            refuse(
              new UpgradePrecondition(
                plan.refusals[0]?.code ?? 'INIT_UPGRADE_REFUSED',
                plan.refusals.map((entry) => entry.message).join('; '),
                'Declare each named key in the adopter policy source and bump policy_version, or retire it deliberately with init bind --adopter-policy <source> --as-role architect --write; then rerun init upgrade.',
                {
                  from: plan.from,
                  to: plan.to,
                  retired_keys: plan.retired_keys.map(pointerKey),
                  refusals: plan.refusals,
                },
              ),
              human,
            );
            return;
          }
          if (plan.status === 'no-op') {
            emit(
              { plan, ...(recovered !== null && { recovered_interrupted_bind: recovered }) },
              human,
              `init upgrade: ${plan.from} is current; nothing to do`,
            );
            process.exitCode = EXIT_PASS;
            return;
          }
          const result = applyAdopterUpgrade(targetRoot, prepared);
          emit(
            {
              plan,
              receipt_path: UPGRADE_RECEIPT,
              ...result,
              ...(recovered !== null && { recovered_interrupted_bind: recovered }),
            },
            human,
            `${humanPlan(plan)}\ninit upgrade: ${plan.from} -> ${plan.to} applied; receipt ${UPGRADE_RECEIPT}`,
          );
          process.exitCode = EXIT_PASS;
        } catch (error) {
          if (error instanceof UpgradePrecondition) {
            refuse(error, human);
            return;
          }
          if (error instanceof UpgradePostcheckFailure) {
            process.stderr.write(
              renderCliError(
                cliError({
                  code: 'INIT_UPGRADE_POSTCHECK_FAILED',
                  class: 'gate-fail',
                  exit: 3,
                  message: `doctor checks failed after the upgrade and every write was rolled back: ${error.checks
                    .filter((check) => !check.ok)
                    .map((check) => check.name)
                    .join(', ')}`,
                  remediation: 'Fix the reported findings, then rerun init upgrade --write.',
                  context: {
                    postchecks: POSTCHECKS,
                    failed: error.checks
                      .filter((check) => !check.ok)
                      .map((check) => ({ name: check.name, errors: check.errors ?? [] })),
                  },
                }),
                !human,
              ),
            );
            process.exitCode = EXIT_GATE;
            return;
          }
          process.stderr.write(
            `devai init upgrade: ${error instanceof Error ? error.message : String(error)}\n`,
          );
          process.exitCode = EXIT_FAIL;
        }
      });
  },
});
