import { generateKeyPairSync } from 'node:crypto';
import {
  appendFileSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { checkTrustedLocalRcBoundary } from '../../src/commands/doctor.js';
import { buildCiScaffoldPlan } from '../../src/services/ci-scaffold/index.js';

const roots: string[] = [];

afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

function put(root: string, path: string, value: unknown): void {
  const absolute = join(root, path);
  mkdirSync(dirname(absolute), { recursive: true });
  writeFileSync(
    absolute,
    typeof value === 'string' ? value : `${JSON.stringify(value, null, 2)}\n`,
  );
}

function fixture(): string {
  const root = mkdtempSync(join(tmpdir(), 'devai-doctor-attested-'));
  roots.push(root);
  put(root, '.devai/config/project.json', {
    ci_economy: {
      attested_rc: {
        profile: 'rc',
        transport: 'protected-tag-v1',
        tag_prefix: 'devai-local-evidence/',
        binding: 'exact-tree',
        required_check: 'verified-local-rc',
        failure_mode: 'fail-closed',
        local_only_nodes: ['test:mutation'],
      },
    },
  });
  put(root, 'package.json', {
    scripts: {
      'test:mutation': 'pnpm -r stryker',
      'devai:rc:prepare': 'node tools/devai-rc.mjs prepare',
      'devai:rc:publish': 'node tools/devai-rc.mjs publish',
    },
  });
  put(root, 'test-tasks.json', {
    tasks: [{ nodeId: 'test:mutation', argv: ['pnpm', 'run', 'test:mutation'] }],
  });
  const keys = generateKeyPairSync('ed25519');
  put(root, 'law/policy/devai-local-rc-trust-store.json', {
    schemaVersion: '1.0.0',
    trustedSigners: [
      {
        signerId: 'stynx-inspector-workstation-01',
        publicKeyPem: keys.publicKey.export({ type: 'spki', format: 'pem' }).toString(),
      },
    ],
    revokedSignerIds: [],
  });
  put(root, 'law/policy/devai-local-rc-toolchain.json', { node: '24.15.0', pnpm: '9.15.0' });
  put(root, 'law/policy/devai-local-rc-environment.json', {});
  const plan = buildCiScaffoldPlan({ targetRoot: root });
  mkdirSync(dirname(plan.path), { recursive: true });
  writeFileSync(plan.path, plan.content);
  return root;
}

function healthyBoundary() {
  return {
    name: 'trusted-local-rc-boundary',
    ok: true,
    info: {
      configured: true,
      local_rc_execution_configured: true,
      remote_receipt_verification_configured: true,
      proof_transport_configured: true,
      exact_tree_binding_configured: true,
      signer_trust_configured: true,
      approved_non_revoked_signers: 1,
      remote_workflow_can_execute_local_only_node: false,
      remote_mutation_fallback_configured: false,
      attestation_boundary:
        'trusted signer identity and byte integrity; workstation execution is not independently reproduced by GitHub',
    },
  } as const;
}

describe('doctor trusted local RC boundary', () => {
  it('accepts exact generated bytes and rejects even a one-byte materialized workflow drift', () => {
    const root = fixture();
    const workflow = buildCiScaffoldPlan({ targetRoot: root });
    expect(readFileSync(workflow.path, 'utf8')).toBe(workflow.content);
    expect(checkTrustedLocalRcBoundary(root)).toMatchObject({
      ok: true,
      info: {
        remote_receipt_verification_configured: true,
        proof_transport_configured: true,
        exact_tree_binding_configured: true,
      },
    });

    appendFileSync(workflow.path, ' ');
    const drifted = checkTrustedLocalRcBoundary(root);
    expect(drifted.ok).toBe(false);
    expect(drifted.info).toMatchObject({
      remote_receipt_verification_configured: false,
      proof_transport_configured: false,
      exact_tree_binding_configured: false,
    });
    expect(drifted.errors).toContain(
      'generated trusted local RC verifier workflow is missing or stale',
    );
  });

  it('reports local execution, remote verification, transport, tree binding, signer trust, and no fallback separately', () => {
    const result = checkTrustedLocalRcBoundary(fixture());
    expect(result).toEqual(healthyBoundary());
  });

  it('inspects both workflow extensions while ignoring non-workflow files', () => {
    const root = fixture();
    const prohibited =
      'on: workflow_dispatch\njobs:\n  mutation:\n    steps:\n      - run: pnpm exec stryker run\n';
    put(root, '.github/workflows/notes.txt', prohibited);
    expect(checkTrustedLocalRcBoundary(root)).toEqual(healthyBoundary());

    put(root, '.github/workflows/hardening.yaml', prohibited);
    expect(checkTrustedLocalRcBoundary(root)).toEqual({
      ...healthyBoundary(),
      ok: false,
      info: {
        ...healthyBoundary().info,
        remote_workflow_can_execute_local_only_node: true,
      },
      errors: ['hardening.yaml: direct Stryker invocation'],
    });
  });

  it('does not count an explicitly revoked anonymous signer as approved', () => {
    const root = fixture();
    const keys = generateKeyPairSync('ed25519');
    put(root, 'law/policy/devai-local-rc-trust-store.json', {
      schemaVersion: '1.0.0',
      trustedSigners: [
        {
          publicKeyPem: keys.publicKey.export({ type: 'spki', format: 'pem' }).toString(),
        },
      ],
      revokedSignerIds: [''],
    });

    expect(checkTrustedLocalRcBoundary(root)).toEqual({
      ...healthyBoundary(),
      ok: false,
      info: {
        ...healthyBoundary().info,
        remote_receipt_verification_configured: false,
        signer_trust_configured: false,
        approved_non_revoked_signers: 0,
      },
      errors: ['approved non-revoked local RC signer trust is missing'],
    });
  });

  it('fails when any workflow can execute mutation', () => {
    const root = fixture();
    put(
      root,
      '.github/workflows/hardening.yml',
      'on: workflow_dispatch\njobs:\n  mutation:\n    steps:\n      - run: pnpm exec stryker run\n',
    );
    const result = checkTrustedLocalRcBoundary(root);
    expect(result.ok).toBe(false);
    expect(result.info).toMatchObject({ remote_workflow_can_execute_local_only_node: true });
    expect(result.errors?.join('\n')).toContain('direct Stryker invocation');
  });
});
